// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2JTHmmNfI-fvmw1OmLCvDlpY0GeqmLLo',
    appId: '1:474237274381:web:52e8070efcdd405e4f4844',
    messagingSenderId: '474237274381',
    projectId: 'blearning-system-app',
    authDomain: 'blearning-system-app.firebaseapp.com',
    storageBucket: 'blearning-system-app.appspot.com',
    measurementId: 'G-XR3YYKY4QN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvGs2bp5IkIKhCqkZyLAIUzClwUk7Y4lY',
    appId: '1:474237274381:android:8418c94e002e255f4f4844',
    messagingSenderId: '474237274381',
    projectId: 'blearning-system-app',
    storageBucket: 'blearning-system-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZSlnMDtA_gLnngbNGHMDOu6oB-b2044',
    appId: '1:474237274381:ios:26053ee7df7ad3264f4844',
    messagingSenderId: '474237274381',
    projectId: 'blearning-system-app',
    storageBucket: 'blearning-system-app.appspot.com',
    iosClientId: '474237274381-kj8k7bvofjtgm5o1khpapov8m8nmfbin.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClZSlnMDtA_gLnngbNGHMDOu6oB-b2044',
    appId: '1:474237274381:ios:26053ee7df7ad3264f4844',
    messagingSenderId: '474237274381',
    projectId: 'blearning-system-app',
    storageBucket: 'blearning-system-app.appspot.com',
    iosClientId: '474237274381-kj8k7bvofjtgm5o1khpapov8m8nmfbin.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylearning',
  );
  
}
